### ISSUE TITLE
conda-forge package & inclusion in MNE-Python installer

### ISSUE THREAD

**Issue by hoechenberger** [john-veillette/mne-ari#2]
Hello @john-veillette, amazing project!

I've started work on a `conda-forge` package at https://github.com/conda-forge/staged-recipes/pull/18197 so a broader audience will be able to easily use this! Would you like to be listed as a co-maintainer of the package? You don't need to know much about `conda-forge` really; maintenance mostly boils down to updating the dependencies once in a while if they have changed.

Also, we're planning on [including](https://github.com/hoechenberger/mne-installers/issues/72) the package in the upcoming stand-alone installer packages for MNE-Python. This would give you more visibility.

Do you know if MNE-ARI is already compatible with the soon-to-be-released MNE-Python 1.0, and with Python 3.10?

Best wishes,

Richard

cc @larsoner

**Comment by john-veillette** [comment]
Hi @hoechenberger,

Sounds great! Yeah, I don't know too much about conda-forge, other than that I should usually put it at the top of my environment files :) but I can definitely keep dependencies up-to-date. 

MNE-ARI's CI pipeline runs the unit tests on the most recent released version of MNE and of Python each time I push my commits, so I'm certain the package runs on Python 3.10 but not 100% certain it runs with MNE 1.0. Like MNE's statistics functions, MNE-ARI acts directly on numpy arrays rather than on e.g. mne.Epochs objects, so the crux of the dependency on MNE is just for handling clustering. I haven't run into any deprecation warnings, so I'm pretty confident this will continue to work but can't guarantee it at the moment. Happy to test the package with the development version of MNE to make sure.

John

**Comment by john-veillette** [comment]
@hoechenberger re: MNE-Python 1.0 compatibility, I've updated the CI workflow to test against the latest `mne` code on GH instead of just the stable version, and the unit tests are still passing. So it seems like everything's in order there.

**Comment by hoechenberger** [comment]
Great! Thanks for looking into this!!

**Comment by hoechenberger** [comment]
The package is now on conda-forge (feedstock: https://github.com/conda-forge/mne-ari-feedstock) and included will be included in the MNE Installers. Thank you!
